### ISSUE TITLE
Rename the repo to make it editor agnostic?

### ISSUE THREAD

**Issue by trivikr** [nodejs/node-code-ide-configs#1]
This was suggested by @devsnek in https://github.com/nodejs/admin/issues/260#issuecomment-434941345
How about renaming it to **node-editor-config**?

**Comment by trivikr** [comment]
Suggestion from @refack: `node-code-ide-configs`
Comment: https://github.com/nodejs/admin/issues/260#issuecomment-435068470

**Comment by refack** [comment]
I'm fine with suggestions.

**Comment by trivikr** [comment]
cc @nodejs/tsc for renaming the repo to `node-code-ide-configs` as agreed in https://github.com/nodejs/TSC/issues/633

**Comment by Trott** [comment]
Renamed.
